console.clear();
import express from 'express';
import dotenv from 'dotenv';
import accountRouters from './routes/account.js';
import authRouter from './routes/auth.js';
dotenv.config();
const port = process.env.Port || 3000;
const app = express();
app.use(express.json());
app.use(express.text());
app.use('/account', accountRouters);
app.use('/auth', authRouter);
app.listen(port, () => console.log(`servidor en el puerto ${port}`));
